name: permission_manager
description: A Flutter plugin to check and request app permissions on Android and iOS using a unified and simple API.
version: 2.0.3
homepage: https://github.com/manojprajapati1999/permission_manager
repository: https://github.com/manojprajapati1999/permission_manager
issue_tracker: https://github.com/manojprajapati1999/permission_manager/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.me.permission_manager
        pluginClass: PermissionManagerPlugin
      ios:
        pluginClass: PermissionManagerPlugin
      web:
        fileName: permission_manager_web.dart
        pluginClass: PermissionManagerWeb
      macos:
        pluginClass: PermissionManagerPlugin
      windows:
        pluginClass: PermissionManagerPlugin
      linux:
        pluginClass: PermissionManagerPlugin
